### ISSUE TITLE
li的边界线技巧

### ISSUE THREAD

**Issue by champkeh** [champkeh/fenote#4]
# li 的边界线技巧
## 单行的li

![single line list item](https://cloud.githubusercontent.com/assets/7316006/19265576/39545108-8fd8-11e6-9a91-9e90c22552ab.png)
### 核心代码

``` css
li + li {
    border-left: 1px solid #ddd;
}
```
## 多行的li

![multi line list item](https://cloud.githubusercontent.com/assets/7316006/19265781/27719544-8fd9-11e6-8561-f14b5a68bd88.png)
### 核心代码

``` css
.ul-container {
    overflow: hidden;
}
ul {
    margin-left: -1px;
}
li {
    border-left: 1px solid #ddd;
}
```

> 多行的li需要在ul外面套一个div，设置这个div的`overflow: hidden;`属性
